import mongoose from "mongoose";
import { Tour } from "./src/models/Tour.js";
import dotenv from "dotenv";

dotenv.config();

const sampleTours = [
  {
    title: "Snorkeling Adventure in Cozumel 5",
    description:
      "Explore vibrant coral reefs and tropical fish in crystal-clear Caribbean waters.",
    destination: "Cozumel, Mexico",
    port: "Cozumel",
    price: 89,
    duration: "3 hours",
    status: "available",
    totalSpots: 20,
    bookedSpots: 5,
    pricing: { adults: 89, children: 59 },
    departureTime: "9:00 AM",
    returnTime: "12:00 PM",
    daysAvailable: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    category: "water",
    rating: 4.8,
    reviews: 245,
    highlights: ["Coral Reefs", "Marine Life", "Professional Guide"],
    includedItems: ["Snorkeling gear", "Boat transport", "Life jacket"],
    image: "https://images.unsplash.com/photo-",
  },
  {
    title: "Ancient Mayan Ruins Expedition",
    description:
      "Discover the rich history of the Mayan civilization with expert guides.",
    destination: "Tulum, Mexico",
    port: "Cozumel",
    price: 119,
    duration: "5 hours",
    status: "available",
    totalSpots: 25,
    bookedSpots: 8,
    pricing: { adults: 119, children: 79 },
    departureTime: "8:00 AM",
    returnTime: "1:00 PM",
    daysAvailable: ["Monday", "Wednesday", "Friday"],
    category: "Cultural",
    rating: 4.9,
    reviews: 312,
    highlights: ["Mayan Ruins", "Guided Tour", "Scenic Views"],
    includedItems: ["Transport", "Guide", "Water Bottle"],
    image: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a",
  },
  {
    title: "Alaskan Glacier Helicopter Tour",
    description: "Fly over breathtaking glaciers and snow-capped mountains.",
    destination: "Juneau, Alaska",
    port: "Juneau",
    price: 349,
    duration: "2 hours",
    status: "available",
    totalSpots: 12,
    bookedSpots: 6,
    pricing: { adults: 349, children: 299 },
    departureTime: "10:00 AM",
    returnTime: "12:00 PM",
    daysAvailable: ["Tuesday", "Thursday", "Saturday"],
    category: "Adventure",
    rating: 5.0,
    reviews: 198,
    highlights: ["Helicopter Ride", "Glacier Landing", "Photography"],
    includedItems: ["Safety Gear", "Guide"],
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
  },
  {
    title: "Rome Highlights & Colosseum Tour",
    description:
      "Explore iconic landmarks including the Colosseum and Roman Forum.",
    destination: "Rome, Italy",
    port: "Civitavecchia",
    price: 149,
    duration: "7 hours",
    status: "available",
    totalSpots: 30,
    bookedSpots: 14,
    pricing: { adults: 149, children: 99 },
    departureTime: "7:30 AM",
    returnTime: "2:30 PM",
    daysAvailable: ["Daily"],
    category: "Cultural",
    rating: 4.8,
    reviews: 522,
    highlights: ["Colosseum", "Roman Forum", "Historic Sites"],
    includedItems: ["Transport", "Guide", "Entry Tickets"],
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5",
  },
  {
    title: "Santorini Sunset Cruise",
    description:
      "Sail along volcanic islands and enjoy a magical Greek sunset.",
    destination: "Santorini, Greece",
    port: "Santorini",
    price: 129,
    duration: "4 hours",
    status: "available",
    totalSpots: 40,
    bookedSpots: 18,
    pricing: { adults: 129, children: 89 },
    departureTime: "4:00 PM",
    returnTime: "8:00 PM",
    daysAvailable: ["Daily"],
    category: "Water Sports",
    rating: 4.9,
    reviews: 412,
    highlights: ["Sunset", "Volcanic Islands", "Swimming"],
    includedItems: ["Cruise", "Dinner", "Drinks"],
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff",
  },
  {
    title: "Dolphin Encounter Experience",
    description:
      "Interact with friendly dolphins in a safe marine environment.",
    destination: "Nassau, Bahamas",
    port: "Nassau",
    price: 99,
    duration: "2.5 hours",
    status: "available",
    totalSpots: 20,
    bookedSpots: 7,
    pricing: { adults: 99, children: 79 },
    departureTime: "9:30 AM",
    returnTime: "12:00 PM",
    daysAvailable: ["Daily"],
    category: "Water Sports",
    rating: 4.7,
    reviews: 340,
    highlights: ["Dolphins", "Marine Education", "Photos"],
    includedItems: ["Entry Ticket", "Guide"],
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5",
  },
  {
    title: "Norwegian Fjord Kayaking Adventure",
    description:
      "Paddle through stunning fjords surrounded by dramatic landscapes.",
    destination: "Bergen, Norway",
    port: "Bergen",
    price: 139,
    duration: "4 hours",
    status: "available",
    totalSpots: 16,
    bookedSpots: 4,
    pricing: { adults: 139, children: 109 },
    departureTime: "8:00 AM",
    returnTime: "12:00 PM",
    daysAvailable: ["Monday", "Thursday"],
    category: "Water Sports",
    rating: 4.9,
    reviews: 145,
    highlights: ["Kayaking", "Fjords", "Wildlife"],
    includedItems: ["Kayak", "Safety Equipment"],
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
  },
  {
    title: "Tokyo City Discovery",
    description: "Experience the vibrant culture and modern wonders of Tokyo.",
    destination: "Tokyo, Japan",
    port: "Yokohama",
    price: 159,
    duration: "8 hours",
    status: "available",
    totalSpots: 35,
    bookedSpots: 12,
    pricing: { adults: 159, children: 119 },
    departureTime: "8:00 AM",
    returnTime: "4:00 PM",
    daysAvailable: ["Daily"],
    category: "Cultural",
    rating: 4.8,
    reviews: 411,
    highlights: ["Shibuya", "Temple Visit", "Tokyo Tower"],
    includedItems: ["Transport", "Guide"],
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf",
  },
  {
    title: "Bali Temple & Rice Terrace Tour",
    description: "Visit sacred temples and breathtaking rice terraces.",
    destination: "Bali, Indonesia",
    port: "Benoa",
    price: 89,
    duration: "6 hours",
    status: "available",
    totalSpots: 25,
    bookedSpots: 9,
    pricing: { adults: 89, children: 59 },
    departureTime: "9:00 AM",
    returnTime: "3:00 PM",
    daysAvailable: ["Daily"],
    category: "Cultural",
    rating: 4.8,
    reviews: 376,
    highlights: ["Temples", "Rice Fields", "Local Culture"],
    includedItems: ["Transport", "Guide"],
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4",
  },
  {
    title: "Barcelona Tapas & Wine Experience",
    description: "Taste authentic Spanish tapas paired with regional wines.",
    destination: "Barcelona, Spain",
    port: "Barcelona",
    price: 109,
    duration: "3 hours",
    status: "available",
    totalSpots: 20,
    bookedSpots: 11,
    pricing: { adults: 109, children: 69 },
    departureTime: "5:00 PM",
    returnTime: "8:00 PM",
    daysAvailable: ["Daily"],
    category: "Cultural",
    rating: 4.9,
    reviews: 223,
    highlights: ["Wine Tasting", "Tapas", "Local Cuisine"],
    includedItems: ["Food", "Wine", "Guide"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
  },
  {
    title: "African Safari Game Drive makago",
    description:
      "Observe lions, elephants, and zebras in their natural habitat.",
    destination: "Port Elizabeth, South Africa",
    port: "Port Elizabeth",
    price: 199,
    duration: "8 hours",
    status: "available",
    totalSpots: 18,
    bookedSpots: 10,
    pricing: { adults: 199, children: 149 },
    departureTime: "6:00 AM",
    returnTime: "2:00 PM",
    daysAvailable: ["Tuesday", "Thursday", "Saturday"],
    category: "Adventure",
    rating: 5.0,
    reviews: 287,
    highlights: ["Big Five", "Safari Vehicle", "Photography"],
    includedItems: ["Transport", "Lunch", "Guide"],
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801",
  },

  // Add more tours...
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    await Tour.insertMany(sampleTours);
    console.log("✅ Database seeded successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seeding failed:", error);
    process.exit(1);
  }
}

seed();
